---
name: Phone Finder
run-name: ${{ inputs.price }}

on:
  workflow_dispatch:
    inputs:
      price:
        description: Price
        default: 300
      keywords:
        description: Keywords
        default: ""

jobs:
  find-laptops:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List Phones
        shell: bash
        run: python main.py --price "${{ inputs.price }}" --keywords "${{ inputs.keywords }}" | tee "$GITHUB_STEP_SUMMARY"
